name: Build Base docker image 
on:
  schedule:
    # ┌───────────── min (0 - 59)
    # │ ┌────────────── hour (0 - 23)
    # │ │ ┌─────────────── day of month (1 - 31)
    # │ │ │ ┌──────────────── month (1 - 12)
    # │ │ │ │ ┌───────────────── day of week (0 - 6) (0 to 6 are Sunday to Saturday, or use names; 7 is Sunday, the same as 0)
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * *  command to execute / Datetime is UTC-0 / KST 02:00 AM
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    branches: [ "profiler_each_function" ]
  pull_request:
    branches: [ "profiler_each_function" ]


jobs:
  Dependency_Build:
    name: Base docker image
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: pre-build 3rdParty libs 
        run: |
          echo "=== Build start ==="
          cd ${{ github.workspace }}/dockerfiles
          echo "=== Log Docker image status ==="
          echo minn2263 | sudo -S echo ""
          sudo docker images 
          echo "=== Temporary Docker image build start ==="              
          sudo docker build --force-rm --no-cache -t slam:base_temp . -f base.dockerfile
          echo "=== Temporary Docker image build finished ==="
          echo "=== Log Docker image status ==="

          sudo docker images
          echo "=== Replace old Docker image with temporary image start ==="
          sudo docker rmi slam:base
          sudo docker image tag slam:base_temp slam:base
          sudo docker rmi slam:base_temp
          sudo docker images 
          echo "=== Job finished ===" 
