name: test
on:
  workflow_dispatch:


jobs:
  Dependency_Build:
    name: Base docker image
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: pre-build 3rdParty libs 
        run: |
          echo "=== Build start ==="
          echo minn2263 | sudo -S echo ""         
          cd dockerfiles     
          sudo docker start orbslam2
          echo "=== Job finished ===" 

      - name: Clean up Docker image if build fails
        run: |
          echo "=== Clean up start ==="  
          echo minn2263 | sudo -S echo "" 
          echo "=== Log Docker image status ==="
          sudo docker images 
          sudo docker rmi -f $(sudo docker images -f "dangling=true" -q)
          echo "=== Delete dangling Docker images ===" 
          echo "=== Log Docker image status ==="
          sudo docker images
          echo "=== Clean up finished ==="
        if: failure() 
